### ISSUE TITLE
Option to where NPCs do not spawn in players view?

### ISSUE THREAD

**Issue by CombineSlayer24** [Snorps/npcinvasion#4]
Is it possible to add a command option to where NPCs should not spawn in the player(s) view when enabled?

Like If enabled, NPCs should try to spawn out of the players view, if the addon can't spawn NPCs because there are multiple players looking at a large field, they should spawn somewhere where they can't be spotted.

If disabled, then NPCs will spawn like they do now.

I hope that made sense in that explanation.

**Comment by Snorps** [comment]
This would probably require raycasts or a similar technique to get working right, which is a bit outside the scope of this project for the time being.

Thanks for the suggestion, though.
