### ISSUE TITLE
NPC Spawn Delay not working properly?

### ISSUE THREAD

**Issue by HoneyBadger1337** [Snorps/npcinvasion#7]
As far as I can see, changing the NPC Spawn Delay via Console _and_ the Q menu makes no difference, can be 1, 30, 60, 120 seconds, but it will **always** default to 5 seconds, no matter what you change it to. I had to count it to make sure I wasn't going crazy.

https://www.youtube.com/watch?v=tGGmO82WMuI

**Comment by mainplate** [comment]
really has to get fixed

**Comment by mainplate** [comment]
doubt that the devs will reply to this though

**Comment by Snorps** [comment]
We will take a look.

**Comment by Snorps** [comment]
Working for us as of latest update. Try the latest version and see if the problem persists.

**Comment by Snorps** [comment]
you have to tell us what graphics mods ur using btw!!!

**Comment by HoneyBadger1337** [comment]
Thanks will do!

The graphics mod is actually not a mod on the workshop, but a separate software called ReShade! Works for all kinds of games, but I have modified my pack to look different (I originally wanted a 'realistic' look but I've just been tweaking it since). Can be installed via this video but if you want the specific preset I've been tweaking, I'm happy to share it!

https://www.youtube.com/watch?v=XASQYXgVXtw

**Comment by HoneyBadger1337** [comment]
Also, can confirm seems to be working without any issue now, thanks Snorps. Hopefully you'll enjoy the Reshade stuff too.
